---
# Synopsis: Azure resource must have an valid env tag set.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Org.Azure.Tags
spec:
  with:
    - PSRule.Rules.Azure\Azure.Resource.SupportsTags
  condition:
    allOf:
      - in:
          - "dev"
          - "development"
          - "prod"
          - "production"
        field: "tags.environment"
      - in:
          - "low"
          - "medium"
          - "high"
          - "business unit-critical"
          - "mission-critical"
        field: "tags.criticality"
