name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  psrule-scan:
    name: psrule-scan
    runs-on: ubuntu-latest
    permissions:
      issues: read
      checks: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
