name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Bicep for linting
        uses: azure/CLI@v1
        with:
          inlineScript: az config set bicep.use_binary_from_path=false && az bicep build -f bicep/main.bicep --stdout
          
      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@v1
        id: msdo
        with:
          config: .gdnconfig
          tools: templateanalyzer
          categories: 'IaC'

      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}