name: Continuous Integration

on:
  push:
    paths:
      - "bicep/**"
      - "!bicep/abbreviations.json" # Ignore changes to abbreviations.json
      - ".github/**"
  pull_request:
    branches:
      - main
    paths:
      - "bicep/**"
      - "!bicep/abbreviations.json"
      - ".github/**"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      checks: write
      contents: read
      pull-requests: write
    strategy:
      matrix:
        environment: [development, production] # Modify this to match your environments
    env:
      BICEP_ENV_DIR: bicep/environments/${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bicep lint
        run: |
          az bicep lint --file main.bicep
        working-directory: ${{ env.BICEP_ENV_DIR }}
      
      - name: Bicep build
        run: |
          az bicep build --file main.bicep --outfile main.json
          az bicep build-params --file main.bicepparam --outfile main.parameters.json
        working-directory: ${{ env.BICEP_ENV_DIR }}

      - name: Run PSRule
        uses: microsoft/ps-rule@v2.9.0
        with:
          inputPath: ${{ env.BICEP_ENV_DIR }}/main*.json
          modules: "PSRule.Rules.Azure"
          outputFormat: NUnit3 
          outputPath: psrule-results-${{ matrix.environment }}-${{ github.run_number }}.xml
          summary: true

      - name: Publish results
        uses: EnricoMi/publish-unit-test-result-action@v2.11.0
        if: always()
        with:
          check_name: PSRule Scan Results - ${{ matrix.environment }}
          nunit_files: psrule-results-${{ matrix.environment }}-${{ github.run_number }}.xml
          comment_mode: always
          fail_on: test failures
          action_fail: false
          ignore_runs: false
          job_summary: false
          compare_to_earlier_commit: true
          check_run_annotations: all tests, skipped tests

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: psrule-results-${{ matrix.environment }}-run-${{ github.run_number }}
          path: psrule-results-${{ matrix.environment }}-${{ github.run_number }}.xml

  # This job will only run if the workflow is triggered by a pull request
  generate-bicep-docs:
    runs-on: ubuntu-latest
    needs: validate-bicep
    permissions: 
      contents: write
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install necessary modules
        shell: pwsh
        run: |
          Install-Module -Name PSDocs -Force
          Install-Module -Name PSDocs.Azure -Force

      - name: Add execute permissions to Powershell script
        run: chmod u+x ./.github/scripts/generate_bicep_docs.ps1

      - name: Run PowerShell script
        shell: pwsh
        run: ./.github/scripts/generate_bicep_docs.ps1

      - name: Check for changes in bicep directory
        id: git-diff
        run: |
          git diff --exit-code --quiet bicep/ || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add bicep
          git commit -m 'Update bicep documentation'
          git push
