# File: deploy.yaml
name: Deploy Azure Infrastructure
on:
  workflow_dispatch:
    inputs:
      deployment_stack:
        description: "Name of the deployment stack to create/update."
        required: true
        type: string

      location:
        description: "Azure region to store the deployment stack."
        required: true
        type: choice
        options:  # Modify this list to include the Azure regions you want to support
          - "northeurope"
          - "westeurope"
          - "italynorth"
          - "francesouth"
          - "francecentral"
          - "germanynorth"
          - "germanywestcentral"
          - "switzerlandnorth"
        default: "northeurope"

      environment:
        description: "Environment to deploy the stack to."
        type: environment

      deny_settings_mode:
        description: "Defines which operations are denied on resources managed by the stack."
        required: true
        type: choice
        options:
          - "none"
          - "denyDelete"
          - "denyWriteAndDelete"
        default: "none"

      action_on_unmanage:
        description: "Defines what happens to resources that are no longer managed after the stack is updated or deleted."
        required: true
        type: choice
        options:
          - "deleteAll"
          - "deleteResources"
          - "detachAll"
        default: "deleteAll"

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      environment: ${{ inputs.environment }}
    permissions:
      issues: read
      checks: write
      contents: write
      pull-requests: write

  deploy-infra:
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate deployment stack
        run: |
          az stack sub validate \
          --name ${{ inputs.deployment_stack }} \
          --location ${{ inputs.location }} \
          --deny-settings-mode ${{ inputs.deny_settings_mode }} \
          --action-on-unmanage ${{ inputs.action_on_unmanage }} \
          --template-file main.bicep \
          --parameters main.bicepparam
        working-directory: bicep/environments/${{ inputs.environment }}

      - name: Create/Update deployment stack
        run: |
          az stack sub create \
          --name ${{ inputs.deployment_stack }} \
          --location ${{ inputs.location }} \
          --deny-settings-mode ${{ inputs.deny_settings_mode }} \
          --action-on-unmanage ${{ inputs.action_on_unmanage }} \
          --template-file main.bicep \
          --parameters main.bicepparam \
          --yes
        working-directory: bicep/environments/${{ inputs.environment }}
