name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  validate-bicep:
    uses: ./.github/workflows/validate.yaml
    secrets: inherit
  
  deploy-infra:
    needs: validate-bicep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
