# File: destroy.yaml

name: Destroy Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      deployment_stack:
        description: "Name of the deployment stack to delete."
        required: true
        type: string

      environment:
        description: "Environment to destroy."
        type: environment
        required: true

      delete_all:
        description: "Delete rather than detach the stack's resources and resource groups."
        required: true
        type: choice
        options:
          - "true"
          - "false"
        default: "true"

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  approve-destruction:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1.9.0
        with:
          approvers: christosgalano
          minimum-approvals: 1
          issue-title: "Delete deployment stack ${{ inputs.deployment_stack }} in ${{ inputs.environment }}"
          issue-body: "Please approve or deny the destruction of the infrastructure regarding deployment stack **${{ inputs.deployment_stack }}** in the **${{ inputs.environment }}** environment."
          secret: ${{ secrets.GITHUB_TOKEN }}

  destroy-infra:
    runs-on: ubuntu-latest
    needs: approve-destruction
    permissions:
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete deployment stack
        run: |
          az stack sub delete \
          --name ${{ inputs.deployment_stack }} \
          --delete-all ${{ inputs.delete_all }} \
          --yes
