# File: generate-bicep-docs.yaml

name: Generate Bicep Documentation

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-bicep-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download bicep-docs
        run: |
          latest_version=$(curl -s "https://api.github.com/repos/christosgalano/bicep-docs/releases/latest" | jq -r .tag_name)
          wget https://github.com/christosgalano/bicep-docs/releases/download/$latest_version/bicep-docs_linux_amd64.tar.gz -O bicep-docs.tar.gz
          tar xzf bicep-docs.tar.gz
          chmod +x bicep-docs
          mv bicep-docs /usr/local/bin

      - name: Run bicep-docs
        run: bicep-docs --input ./bicep --verbose

      - name: Check for changes in bicep directory
        id: git-diff
        run: |
          change=false
          if git status --porcelain | grep -E 'bicep/.*/README.md'; then
            change=true
          fi
          echo "changed=$change" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add bicep
          git commit -m "Update documentation"
          git push
