name: Generate Bicep Documentation

on:
  push:
    branches-ignore: 
      - main
    paths:
      - "bicep/**"
      - "!bicep/abbreviations.json"
      - ".github/workflows/generate_docs.yaml"
      - ".github/scripts/generate_bicep_docs.ps1"
  pull_request:
    branches:
      - main
    paths:
      - "bicep/**"
      - "!bicep/abbreviations.json"
      - ".github/workflows/generate_docs.yaml"
      - ".github/scripts/generate_bicep_docs.ps1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install necessary modules
        shell: pwsh
        run: |
          Install-Module -Name PSDocs -Force
          Install-Module -Name PSDocs.Azure -Force

      - name: Add execute permissions to Powershell script
        run: chmod u+x ./.github/scripts/generate_bicep_docs.ps1

      - name: Run PowerShell script
        shell: pwsh
        run: ./.github/scripts/generate_bicep_docs.ps1

      - name: Check for changes in bicep directory
        id: git-diff
        run: |
          git diff --exit-code --quiet bicep/ || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add bicep
          git commit -m 'Update bicep documentation'
          git push
