name: Generate Bicep Documentation

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install necessary modules
      shell: pwsh
      run: |
        Install-Module -Name PSDocs -Force
        Install-Module -Name PSDocs.Azure -Force

    - name: Add execute permissions to Powershell script
      run: chmod u+x ./.github/scripts/generate_bicep_docs.ps1

    - name: Run PowerShell script
      run: ./.github/scripts/generate_bicep_docs.ps1

    - name: Check for changes
      id: git-diff
      run: |
        git diff --exit-code --quiet || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if there are changes
      if: steps.git-diff.outputs.changed == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add bicep/abbreviations.json
        git commit -m 'Update bicep documentation'
        git push
