name: Validate Bicep

on:
  push:
    paths:
      - "bicep/**"
      - "!bicep/abbreviations.json" # Ignore changes to abbreviations.json
      - ".github/workflows/validate.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "bicep/**"
      - "!bicep/abbreviations.json"
      - ".github/workflows/validate.yaml"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      checks: write
      contents: read
      pull-requests: write
    strategy:
      matrix:
        environment: [development, production] # Modify this to match your environments
    env:
      BICEP_ENV_DIR: bicep/environments/${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bicep lint
        run: |
          az bicep lint --file main.bicep
        working-directory: ${{ env.BICEP_ENV_DIR }}
      
      - name: Bicep build
        run: |
          az bicep build --file main.bicep --outfile main.json
          az bicep build-params --file main.bicepparam --outfile main.parameters.json
        working-directory: ${{ env.BICEP_ENV_DIR }}

      - name: Run PSRule
        uses: microsoft/ps-rule@v2.9.0
        with:
          inputPath: ${{ env.BICEP_ENV_DIR }}/main*.json
          modules: "PSRule.Rules.Azure"
          outputFormat: NUnit3 
          outputPath: psrule-results-${{ matrix.environment }}-${{ github.run_number }}.xml
          summary: true

      - name: Publish results
        uses: EnricoMi/publish-unit-test-result-action@v2.11.0
        if: always()
        with:
          check_name: PSRule Scan Results - ${{ matrix.environment }}
          nunit_files: psrule-results-${{ matrix.environment }}-${{ github.run_number }}.xml
          comment_mode: always
          fail_on: test failures
          action_fail: false
          ignore_runs: false
          job_summary: false
          compare_to_earlier_commit: true
          check_run_annotations: all tests, skipped tests

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: psrule-results-${{ matrix.environment }}-run-${{ github.run_number }}
          path: psrule-results-${{ matrix.environment }}-${{ github.run_number }}.xml
